# Generated by Django 4.1.5 on 2023-01-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=200)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('AutoMobile', 'AutoMobile'), ('Steel', 'Steel')], max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
